<#
    Module manifest for module 'PsiPS.AzureAutomation'
    Generated by: Kevin Cefalu, PsiBit Development
    Generated on: 2019-09-17
#>

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'PsiPS.AzureAutomation';

    # Version number of this module.
    ModuleVersion = '0.3.0';

    # Supported PSEditions
    # CompatiblePSEditions = @();

    # ID used to uniquely identify this module
    GUID = '3ba5322e-c346-4250-b607-5609c77bec1c';

    # Author of this module
    Author = 'Kevin Cefalu';

    # Company or vendor of this module
    CompanyName = 'PsiBit Development';

    # Copyright statement for this module
    Copyright = '(c) 2019 Kevin Cefalu, PsiBit Development. All rights reserved.';

    # Description of the functionality provided by this module
    Description = 'Use this module to work with Azure Automation Accounts.';

    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = '';

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = '';

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = '';

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = '';

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = '';

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = '';

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        @{
            ModuleName = 'AzureRm.Automation';
            ModuleVersion = '6.1.1';
            Guid = 'bcea1c70-a32b-48c3-a05c-323e1c02f4d3';
        }
    );

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @();

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @();

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @();

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @();

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @();

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*';

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = '*';

    # Variables to export from this module
    VariablesToExport = '*';

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = '*';

    # DSC resources to export from this module
    # DscResourcesToExport = @();

    # List of all modules packaged with this module
    # ModuleList = @();

    # List of all files packaged with this module
    # FileList = @();

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        # Place Module feature flags here.
        FeatureFlags = @{ };

        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Azure', 'Automation', 'Runbook');

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/kevinCefalu/PsiPS.AzureAutomation/blob/master/license.txt';

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/kevinCefalu/PsiPS.AzureAutomation';

            # A URL to an icon representing this module.
            # IconUri = '';

            # ReleaseNotes of this module
            # ReleaseNotes = '';
        };
    };

    # HelpInfo URI of this module
    # HelpInfoURI = '';

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = 'PsiAzAuto';
}
